"use client";

import {
  AirplaneLanding,
  At,
  Baby,
  Bed,
  Boat,
  BowlFood,
  Briefcase,
  Buildings,
  Bus,
  Cake,
  CalendarBlank,
  CalendarDots,
  CarProfile,
  Champagne,
  ChatsTeardrop,
  ChatText,
  CheckSquare,
  Clock,
  Coffee,
  Compass,
  EnvelopeSimple,
  FirstAid,
  Flag,
  Flower,
  FlowerLotus,
  ForkKnife,
  Globe,
  Hash,
  House,
  Images,
  ListChecks,
  MapPin,
  MapTrifold,
  MegaphoneSimple,
  Paperclip,
  Phone,
  Plug,
  Presentation,
  Question,
  RadioButton,
  Rows,
  Scroll,
  ShoppingBag,
  Signpost,
  Star,
  Suitcase,
  TextAlignLeft,
  TextT,
  ToggleLeft,
  Train,
  Umbrella,
  User,
  UsersThree,
  Van,
  type Icon,
  type IconWeight,
} from "@phosphor-icons/react";

const MAP: Record<string, Icon> = {
  AirplaneLanding,
  At,
  Baby,
  Bed,
  Boat,
  BowlFood,
  Briefcase,
  Buildings,
  Bus,
  Cake,
  CalendarBlank,
  CalendarDots,
  CarProfile,
  Champagne,
  ChatsTeardrop,
  ChatText,
  CheckSquare,
  Clock,
  Coffee,
  Compass,
  EnvelopeSimple,
  FirstAid,
  Flag,
  Flower,
  FlowerLotus,
  ForkKnife,
  Globe,
  Hash,
  House,
  Images,
  ListChecks,
  MapPin,
  MapTrifold,
  MegaphoneSimple,
  Paperclip,
  Phone,
  Plug,
  Presentation,
  Question,
  RadioButton,
  Rows,
  Scroll,
  ShoppingBag,
  Signpost,
  Star,
  Suitcase,
  TextAlignLeft,
  TextT,
  ToggleLeft,
  Train,
  Umbrella,
  User,
  UsersThree,
  Van,
};

/** A Phosphor icon by name, for catalogue entries that name their glyph. */
export function CatalogIcon({ name, size = 16, weight = "regular", className }: { name: string; size?: number; weight?: IconWeight; className?: string }) {
  const I = MAP[name] ?? Rows;
  return <I size={size} weight={weight} className={className} aria-hidden />;
}
